experiment:
  name: tutorial_80S

dataset:
  # Directory containing tomograms and sidefiles 
  path: ../tm_tutorial/dataset
  
  # Dataset type: tutorial, real, or simulated
  type: tutorial
  
particle:
  template_matching_diameter_angstrom: 300
  
  # User-specified extraction diameter (optional, only required for elongated particles, o/w same as TM diameter 
  extraction_diameter_angstrom:
  
  # Use RG-based extraction diameter if extraction diameter is unknown
  extraction_diameter_required: false
  
  # PDB file used for diameter estimation
  pdb:

template:
  # Input density map for template generation
  input: ../tm_tutorial/templates/EMD-2938.map
  
ground_truth:
  directory: ../tm_tutorial/dataset
  
conversion:
  particle_name: ribosome

template_generation:
  # Invert density values during template creation
  invert: true
  output_name: template.mrc
  
template_mask:
  output_name: mask.mrc

template_matching:
  rotational_symmetry: 1
  random_phase_correction: false
  
search_region:
  enabled: false
  x: [0,0]
  y: [0,0]
  z: [0,0]
  
tomogram_mask:
  enabled: true
  directory: ../tm_tutorial/picket_masks

ctf:
  enabled: true
  mode: constant 
  defocus: 3
  amplitude_contrast: 0.08
  spherical_aberration: 2.7
  voltage: 200
  tomogram_ctf_model: phase-flip
  per_tilt_weighting: false
  
tilt_angles:
  min: -60
  max: 60

compute:
  gpu_ids: [0]
  volume_split:
    x: 1
    y: 1
    z: 1
    
execution:
  # Enable or disable pipeline stages
  generate_template: true
  generate_mask: true
  run_template_matching: true
  run_extraction: true
  run_roc: true
  run_conversion: true
  run_evaluation: true
  run_benchmark_summary: true
  
extraction:
  # Number of particles to extract (arbitrarily large number) 
  number_of_particles: 10000
  
  # Score cutoff (blank = PyTOM automatic estimation)
  cutoff:
  
roc:
  # Number of histogram bins for ROC estimation
  bins: 16
  
  # Crop plot around particle peak
  crop_plot: true
